dbfilename redis_queue.rdb
dir /mnt/d/itucedric/L3/S6/Eval/02/erpnextfrappe/config/pids
pidfile /mnt/d/itucedric/L3/S6/Eval/02/erpnextfrappe/config/pids/redis_queue.pid
bind 127.0.0.1
port 11001

aclfile /mnt/d/itucedric/L3/S6/Eval/02/erpnextfrappe/config/redis_queue.acl
